create table PROD (
    prod_no number(12) not null constraint prod_no_pk primary key,
    quality varchar2(4) not null,
    inp_time varchar2(50) not null,
    out_time varchar2(50) not null,
    leftright varchar2(4) not null
    ) tablespace produce;

CREATE TABLE "DEFECTIVE"(
      "PROD_NO" NUMBER(12) NOT NULL, --FK
      "INP_TIME" VARCHAR2(100) NOT NULL,
      "OUT_TIME" VARCHAR2(100) NOT NULL,
        "LR_LABEL" VARCHAR2(10) NOT NULL,
        CONSTRAINT CASCADEDEL 
      FOREIGN KEY (PROD_NO) REFERENCES PROD(PROD_NO)
        ON DELETE CASCADE
)TABLESPACE PRODUCE;

CREATE TABLE EMP(
		ID VARCHAR2(20) NOT NULL CONSTRAINT EMP_ID_PK PRIMARY KEY,
		PWD VARCHAR2(20) NOT NULL,
		EMAIL VARCHAR2(50)
)	TABLESPACE PRODUCE;

CREATE TABLE "DASHBOARD"(
      "PROCESS_NO" NUMBER(10)constraint dash_no_pk primary key,
      "TODAY_COUNT" NUMBER(20),
      "START_TIME" VARCHAR2(100),
      "END_TIME" VARCHAR2(100),
      "ERROR_RATE" VARCHAR2(20),
      "YIELD" VARCHAR2(20)
)TABLESPACE PRODUCE;

CREATE SEQUENCE SEQ_PROD_PRODID
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 9999999999
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_DASH_PROCESSNO
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 9999999999
NOCYCLE
NOCACHE;
